server {
    listen 80;

    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass http://backend:8080;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location ~* (^|/)\.env {
        return 404;
    }

    location ~* /(docker-compose.*\.ya?ml|application.*\.ya?ml|application.*\.properties|secrets.*|credentials.*|config.*|settings.*|appsettings.*|terraform.*|serverless.*|wp-config.*)$ {
        return 404;
    }

    location ~* /(\.git|\.svn|\.hg|\.aws|\.docker|\.gcp|node_modules|vendor)/ {
        return 404;
    }

    location ~* /(actuator|debug|phpmyadmin|wp-admin|wp-login|laravel|storage|backup|backups|old|tmp|temp)/ {
        return 404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}