services:
  database:
    image: postgres:16-alpine
    container_name: checkvitals-database
    environment:
      POSTGRES_DB: checkvitals
      POSTGRES_USER: checkvitals
      POSTGRES_PASSWORD: checkvitals
    volumes:
      - checkvitals_postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: checkvitals-backend
    depends_on:
      - database
    environment:
      SPRING_PROFILES_ACTIVE: docker
    expose:
      - "8080"

  frontend:
    build:
      context: ./frontend
    container_name: checkvitals-frontend
    depends_on:
      - backend
    ports:
      - "7200:80"

volumes:
  checkvitals_postgres_data: