spring:
  datasource:
    url: jdbc:postgresql://database:5432/checkvitals
    driver-class-name: org.postgresql.Driver
    username: checkvitals
    password: checkvitals

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

checkvitals:
  check:
    interval-ms: 300000
    initial-delay-ms: 10000
    lagging-threshold-ms: 1000