spring:
  application:
    name: UptimeWatch

  datasource:
    url: jdbc:h2:file:./data/uptimewatch
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

checkvitals:
  check:
    #5 Minuten = 5 × 60 Sekunden = 300 Sekunden
    #300 Sekunden = 300000 ms
    interval-ms: 300000
    initial-delay-ms: 5000